name = "bug-detective-api"
main = "index.ts"
compatibility_date = "2026-04-18"

# Created via:
#   npx wrangler kv namespace create BUG_LB --use-remote
[[kv_namespaces]]
binding = "BUG_LB"
id = "17b64d560ec84a4c90bb72809d596848"
remote = true
